# Generated by Django 5.2.7 on 2025-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="secretKeys",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user", models.CharField(max_length=255)),
                ("secretKey", models.CharField(max_length=255)),
            ],
        ),
    ]
