# Generated by Django 5.2.7 on 2025-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretkeys",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
