# Generated by Django 5.2.7 on 2025-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_secretkeys_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        help_text="Le nom de l'application", max_length=100
                    ),
                ),
                (
                    "verifciation_token",
                    models.CharField(
                        blank=True,
                        help_text="Le token de verification recu",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Integration Webhook",
                "verbose_name_plural": "Integration Webhook",
            },
        ),
    ]
