# Generated by Django 5.2.7 on 2025-10-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_webhookintegration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookintegration",
            old_name="verifciation_token",
            new_name="verification_token",
        ),
    ]
