# Generated by Django 5.2.7 on 2025-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "server",
            "0004_rename_verifciation_token_webhookintegration_verification_token",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="secretkeys",
            name="notion_bot_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="secretkeys",
            name="notion_workspace_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
